### ISSUE TITLE
Keyboard offset

### ISSUE THREAD

**Issue by utiko** [CBA-LAD365/liveassist-demo-ios#1] opened 2020-08-06 07:37 UTC
There is an issue with a keyboard appearance. Looks like you're adding keyboard offset twice, once for View and once for content inside.

![Screen Recording 2020-08-06 at 10 30 56](https://user-images.githubusercontent.com/4188450/89504287-738cd400-d7d0-11ea-9ae2-81c0c19a6b4e.gif)

**Comment by alewis001** [comment] 2020-08-06 10:40
Hi @utiko, please ensure you are using the 1.3.2 version of the SDK.

In the future, please raise issues without our Support team via the guidance provided on https://support.liveassistfor365.com/hc/en-us/articles/360006113714-Getting-Support.

**Comment by alewis001** [comment] 2020-08-13 10:44
Hi @utiko, I'm going to close this issue assuming you have updated to the latest version of the SDK and the issue is resolved. Please get in touch with our Support team if you experience any issues.

**Closed as completed by alewis001** 2020-08-13 10:44 UTC
